- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
   - squid

- name: Configure Squid
  template:
    src: squid.conf.j2
    dest: /etc/squid3/squid.conf
  notify: restart squid