- name: Create VPC network
  ec2_vpc:
    region: "{{ vpc_region }}"
    state:  present
    resource_tags: { "Name":"{{ prefix }}-vpc", "Environment":"{{ env }}" }
    internet_gateway: yes
    cidr_block: "{{ vpc_cidr }}"
    subnets: "{{ vpc_subnets }}"
  register: vpc

- name: Tag the Internet Gateway
  ec2_tag:
    resource: "{{ vpc.igw_id }}"
    region: "{{ vpc_region }}"
    state: present
    tags:
      Name: "{{ prefix }}-igw"
      Environment: "{{ env }}"
  register: igw

- name: Create subnet variables
  set_fact:
    subnet_public_01: "{{ vpc.subnets.0.id }}"
    subnet_public_02: "{{ vpc.subnets.1.id }}"
    subnet_public_03: "{{ vpc.subnets.2.id }}"
    subnet_private_app_01: "{{ vpc.subnets.3.id }}"
    subnet_private_app_02: "{{ vpc.subnets.4.id }}"
    subnet_private_app_03: "{{ vpc.subnets.5.id }}"

- name: Set up Public Subnets Route Table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ vpc_region }}"
    state: present
    tags:
      Name: "{{ prefix }}-public-rt"
    subnets:
     - "{{ subnet_public_01 }}"
     - "{{ subnet_public_02 }}"
     - "{{ subnet_public_03 }}"
    routes:
     - dest: 0.0.0.0/0
       gateway_id: "{{ vpc.igw_id }}"
  register: public_rtb

- name: Create private DNS zone
  route53_zone:
    vpc_id: "{{ vpc.vpc_id }}"
    vpc_region: "{{ vpc_region }}"
    zone: "{{ vpc_dns_zone }}"
    state: present
  register: vpc_zone