- name: Create an EC2 app instances
  ec2:
    keypair: "{{ ssh_key_name }}"
    group_id: "{{ sg_ec2_app.group_id }}"
    region: "{{ vpc_region }}"
    instance_type: "{{ ec2_app_instance_type }}"
    image: "{{ ec2_app_ami_id }}"
    vpc_subnet_id: "{{ subnet_private_app_01 }}"
    assign_public_ip: no
    wait: True
    wait_timeout: 300
    instance_tags:
      Environment: "{{ env }}"
      Name: "{{ prefix }}-app"
      Role: "App"
      ForAmi: "Yes"
    count_tag:
      Environment: "{{ env }}"
      Role: "App"
      ForAmi: "Yes"
    exact_count: "{{ ec2_app_instance_count }}"
  register: ec2_app

- name: Add new instances to host group
  add_host:
    name: "{{ item.private_ip }}"
    groups: app_servers
    ec2_id: "{{ item.id }}"
  with_items: "{{ ec2_app.instances }}"