- name: Create an EC2 proxy instances
  ec2:
    keypair: "{{ ssh_key_name }}"
    group_id: "{{ sg_ec2_proxy.group_id }}"
    region: "{{ vpc_region }}"
    instance_type: "{{ proxy_instance_type }}"
    image: "{{ proxy_ami_id }}"
    vpc_subnet_id: "{{ subnet_public_03 }}"
    assign_public_ip: yes
    wait: True
    wait_timeout: 300
    instance_tags:
      Environment: "{{ env }}"
      Name: "{{ prefix }}-proxy"
      Role: "Proxy"
    count_tag:
      Environment: "{{ env }}"
      Name: "{{ prefix }}-proxy"
      Role: "Proxy"
    exact_count: 1
  register: ec2_proxy

- name: Update DNS record
  route53:
    command: create
    zone: "{{ vpc_dns_zone }}"
    record: "proxy.{{ vpc_dns_zone }}"
    type: A
    private_zone: True
    vpc_id: "{{ vpc.vpc_id }}"
    value: "{{ ec2_proxy.instances.0.private_ip }}"
    overwrite: yes
  when: ec2_proxy.instances.0 is defined

- name: Add new instances to host group
  add_host:
    name: "{{ item.private_ip }}"
    groups: app_servers
    ansible_user: "{{ remote_user }}"
    ec2_id: "{{ item.id }}"
  with_items: "{{ ec2_proxy.instances }}"