- name: Associate App instances with ELB
  ec2_elb:
    instance_id: "{{ item.id }}"
    ec2_elbs: "{{ elb_app.elb.name }}"
    state: present
    region: "{{ vpc_region }}"
    wait: no
  with_items: "{{ ec2_app_instances }}"

- name: Associate Web instances with ELB
  ec2_elb:
    instance_id: "{{ item.id }}"
    ec2_elbs: "{{ elb_web.elb.name }}"
    state: present
    region: "{{ vpc_region }}"
    wait: no
  with_items: "{{ ec2_web_instances }}"