- name: Install prerequirements
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - software-properties-common

- name: Add ansible repository
  apt_repository: repo='ppa:ansible/ansible'

- name: Install ansible
  apt:
    name: ansible
    update_cache: yes
    state: present

- name: Install PIP
  easy_install:
    name: pip
    state: present

- name: Install Python packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - boto

- name: Copy boto config template
  template: src=boto.j2 dest="/home/vagrant/.boto" owner={{ remote_user }} group={{ remote_user }}

- name: Configure ssh for vagrant user
  template: src=ssh_config.j2 dest="/home/vagrant/.ssh/config" owner={{ remote_user }} group={{ remote_user }} mode=600