- name: Creating a Security Group for ELB
  ec2_group:
    name: "{{ prefix }}-elb-web-sg"
    description: "Only http and https traffic from everywhere"
    region: "{{ vpc_region }}"
    vpc_id: "{{ vpc.vpc_id }}"
    state: present
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
  register: sg_elb_web

- name: Tag Web ELB SG
  ec2_tag:
    resource: "{{ sg_elb_web.group_id }}"
    region: "{{ vpc_region }}"
    state: present
    tags:
      Name: "{{ prefix }}-elb-web-sg"
      Tier: "Web"
      Type: "ELB"
      Environment: "{{ env }}"