- name: Create an EC2 varnish instances
  ec2:
    keypair: "{{ ssh_key_name }}"
    group_id: "{{ sg_ec2_web.group_id }}"
    region: "{{ vpc_region }}"
    instance_type: "{{ ec2_web_instance_type }}"
    image: "{{ ec2_web_ami_id }}"
    vpc_subnet_id: "{{ subnet_public_01 }}"
    assign_public_ip: no
    wait: True
    wait_timeout: 300
    instance_tags:
      Environment: "{{ env }}"
      Name: "{{ prefix }}-web"
      Role: "Web"
      ForAmi: "Yes"
    count_tag:
      Environment: "{{ env }}"
      Role: "Web"
      ForAmi: "Yes"
    exact_count: "{{ ec2_web_instance_count }}"
  register: ec2_web

- name: Add new instances to host group
  add_host:
    name: "{{ item.private_ip }}"
    groups: cache_servers
    ec2_id: "{{ item.id }}"
  with_items: "{{ ec2_web.instances }}"